export const EMAIL_EXISTS = 'EmailId Already Exists'
export const VITE_REACT_APP_HOST = 'http://localhost:3000'
export const VITE_REACT_APP_LOGIN = '/auth/login'
export const VITE_REACT_APP_REGISTER = '/auth/signup'
export const VITE_REACT_APP_LOGOUT = '/auth/logout'
export const VITE_REACT_APP_PROFILE = '/profile/view'
export const VITE_REACT_APP_FEED = '/user/feed'
export const VITE_REACT_APP_EDIT_PROFILE = '/profile/edit'
export const VITE_REACT_APP_USER_CONNECTIONS = '/user/connections'
export const VITE_REACT_APP_IMAGE_UPLOAD = '/image/upload'
export const VITE_REACT_APP_REQUEST_CONNECTIONS = '/user/requests/received'
export const VITE_REACT_APP_REVIEW_REQUESTS = '/request/review'
export const VITE_REACT_APP_SEND_REQUESTS = '/request/send'
export const REVIEW_STATUS_ACCEPTED = "accepted"
export const REVIEW_STATUS_DECLINED = "rejected"
export const SEND_REQUEST_STATUS_INTERESTED = "interested"
export const SEND_REQUEST_STATUS_IGNORED = "ignored"